version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: flip-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flip-url-shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
